# Generated by Django 5.2.10 on 2026-06-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('equipe', models.CharField(choices=[('eventos', 'Eventos'), ('logistica', 'Logística'), ('aconselhamento', 'Aconselhamento'), ('programa', 'Programa'), ('lojinha_cantina', 'Lojinha e Cantina'), ('oracao', 'Oração'), ('comunicacao', 'Comunicação'), ('administracao', 'Administração'), ('financeiro', 'Financeiro'), ('materiais', 'Materiais'), ('pessoal', 'Pessoal')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('equipe', models.CharField(choices=[('eventos', 'Eventos'), ('logistica', 'Logística'), ('aconselhamento', 'Aconselhamento'), ('programa', 'Programa'), ('lojinha_cantina', 'Lojinha e Cantina'), ('oracao', 'Oração'), ('comunicacao', 'Comunicação'), ('administracao', 'Administração'), ('financeiro', 'Financeiro'), ('materiais', 'Materiais'), ('pessoal', 'Pessoal')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='dashboard.membro')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['status', 'prazo', '-criado_em'],
            },
        ),
    ]
