# Generated by Django 5.2.10 on 2026-07-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seed_sample_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('titulo_atividade', models.CharField(max_length=180)),
                ('descricao_atividade', models.TextField(blank=True)),
                ('prazo_entrega', models.DateField(blank=True, null=True)),
                ('external_sync_status', models.CharField(choices=[('nao_configurado', 'Nao configurado'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], default='nao_configurado', max_length=20)),
                ('external_sync_response', models.TextField(blank=True)),
                ('classroom_course_id', models.CharField(blank=True, max_length=120)),
                ('classroom_status', models.CharField(choices=[('nao_enviado', 'Nao enviado'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], default='nao_enviado', max_length=20)),
                ('classroom_coursework_id', models.CharField(blank=True, max_length=120)),
                ('classroom_response', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Preparo',
                'verbose_name_plural': 'Registros de Preparo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
