# Generated by Django 5.2.10 on 2026-07-06 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_preparoregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Camisa SEND ME'), ('Camisa I BELONG TO JESUS')], max_length=20)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=10)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU de inventário',
                'verbose_name_plural': 'SKUs de inventário',
                'ordering': ['color', 'size'],
                'unique_together': {('color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='PreOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=80, unique=True)),
                ('source', models.CharField(choices=[('form', 'Form'), ('sheet', 'Sheet')], default='form', max_length=20)),
                ('volunteer_name', models.CharField(max_length=120)),
                ('color', models.CharField(choices=[('Camisa SEND ME'), ('Camisa I BELONG TO JESUS')], max_length=20)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('importado', 'Importado'), ('sincronizado', 'Sincronizado')], default='reservado', max_length=20)),
                ('sheet_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sheet_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pré-encomenda',
                'verbose_name_plural': 'Pré-encomendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('color', models.CharField(choices=[('Camisa SEND ME'), ('Camisa I BELONG TO JESUS')], max_length=20)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('pix_cash', 'Pix/Cash'), ('card', 'Card')], max_length=20)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de venda',
                'verbose_name_plural': 'Registros de venda',
                'ordering': ['-created_at'],
            },
        ),
    ]
