# Generated by Django 5.2.10 on 2026-07-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_change_size_codes_to_pp_pxg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_link', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de importação de pré-encomendas',
                'verbose_name_plural': 'Configurações de importação de pré-encomendas',
            },
        ),
        migrations.AlterField(
            model_name='inventorysku',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preorderrecord',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preorderrecord',
            name='source',
            field=models.CharField(choices=[('form', 'Formulário'), ('sheet', 'Planilha')], default='form', max_length=20),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='payment_method',
            field=models.CharField(choices=[('pix_cash', 'Pix/Dinheiro'), ('card', 'Cartão')], max_length=20),
        ),
    ]
