# Generated by Django 5.2.10 on 2026-07-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_preordersheetconfig_alter_inventorysku_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix_cash', 'Pix/Dinheiro'), ('card', 'Cartão')], default='', max_length=20),
        ),
    ]
