# Generated by Django 5.2.10 on 2026-07-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_preorderrecord_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderrecord',
            name='payment_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
