# Generated by Django 5.2.10 on 2026-07-06 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_preorderrecord_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AconselhamentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_link', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de aconselhamento',
                'verbose_name_plural': 'Configurações de aconselhamento',
            },
        ),
        migrations.CreateModel(
            name='AconselhamentoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('caracteristica', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('misto', 'Misto')], default='misto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala de aconselhamento',
                'verbose_name_plural': 'Salas de aconselhamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AconselhamentoCampista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], default='', max_length=20)),
                ('grupo', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('origem_planilha', models.CharField(blank=True, max_length=120)),
                ('linha_planilha', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campistas', to='dashboard.aconselhamentosala')),
            ],
            options={
                'verbose_name': 'Campista',
                'verbose_name_plural': 'Campistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AconselhamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=60)),
                ('detalhe', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='dashboard.aconselhamentocampista')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_destino', to='dashboard.aconselhamentosala')),
                ('sala_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_origem', to='dashboard.aconselhamentosala')),
            ],
            options={
                'verbose_name': 'Histórico de aconselhamento',
                'verbose_name_plural': 'Históricos de aconselhamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
