# Generated by Django 5.2.10 on 2026-07-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aconselhamentoconfig_aconselhamentosala_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aconselhamentocampista',
            options={'ordering': ['nome'], 'verbose_name': 'Acampante', 'verbose_name_plural': 'Acampantes'},
        ),
        migrations.RenameField(
            model_name='aconselhamentocampista',
            old_name='grupo',
            new_name='celula',
        ),
    ]
