# Generated by Django 5.2.10 on 2026-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_aconselhamentocampista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aconselhamentosala',
            name='caracteristica',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=20),
        ),
    ]
