# Generated by Django 5.2.10 on 2026-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_aconselhamentosala_caracteristica'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_link', models.URLField(blank=True)),
                ('mirror_mode', models.BooleanField(default=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de importação de membros',
                'verbose_name_plural': 'Configurações de importação de membros',
            },
        ),
    ]
