# Generated by Django 6.0.6 on 2026-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_membrosheetconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysku',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preorderrecord',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto')], max_length=20),
        ),
    ]
