# Generated by Django 5.2.10 on 2026-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chefia', 'CHEFIA'), ('tripe7', 'TRIPÉ')], default='chefia', max_length=20),
        ),
    ]
